import fs from 'node:fs'
import { acrossSeam, area2, fitter, path, robinson, simplify } from './geolib.mjs'

const S = process.argv[2]
const OUT = process.argv[3]
const topo = JSON.parse(fs.readFileSync(`${S}/world.topo.json`, 'utf8'))

const [sx, sy] = topo.transform.scale
const [tx, ty] = topo.transform.translate
function arcPoints(i) {
  const rev = i < 0
  const arc = topo.arcs[rev ? ~i : i]
  let x = 0; let y = 0
  const pts = arc.map(([dx, dy]) => { x += dx; y += dy; return [x * sx + tx, y * sy + ty] })
  return rev ? pts.reverse() : pts
}
const ring = (arcs) => arcs.reduce((out, a) => {
  const pts = arcPoints(a)
  out.push(...(out.length ? pts.slice(1) : pts))
  return out
}, [])
const ringsOf = (g) => (g.type === 'Polygon' ? g.arcs.map(ring) : g.arcs.flat().map(ring))
  .flatMap(acrossSeam)

// The corridors the international book actually travels.
const CORRIDOR = {}
const put = (w, ...cs) => cs.forEach((c) => { CORRIDOR[c] = w })
put('w1', 'United Arab Emirates', 'Saudi Arabia', 'Qatar', 'Oman', 'Kuwait')
put('w2', 'United States of America', 'Canada')
put('w3', 'United Kingdom', 'Ireland', 'France', 'Germany', 'Switzerland', 'Italy', 'Spain',
  'Netherlands', 'Belgium', 'Austria', 'Portugal', 'Greece', 'Czechia', 'Poland', 'Sweden',
  'Norway', 'Denmark', 'Finland', 'Hungary', 'Croatia', 'Luxembourg', 'Slovakia', 'Slovenia')
put('w4', 'Thailand', 'Malaysia', 'Indonesia', 'Vietnam', 'Philippines', 'Cambodia', 'Brunei', 'Laos')
put('w5', 'Japan', 'South Korea', 'China', 'Taiwan', 'Australia', 'New Zealand')
put('w6', 'Nepal', 'Sri Lanka', 'Bangladesh', 'Bhutan')

const ORDER = ['w1', 'w2', 'w3', 'w4', 'w5', 'w6']
const groups = { rest: [], home: [] }
for (const w of ORDER) groups[w] = []

for (const g of topo.objects.countries.geometries) {
  const name = g.properties.name
  // Antarctica is a band across the foot of every world projection and carries
  // nothing; it is left off rather than drawn and ignored.
  if (name === 'Antarctica') continue
  const bucket = name === 'India' ? 'home' : CORRIDOR[name] || 'rest'
  groups[bucket].push(...ringsOf(g))
}

// Countries are kept whole rather than dissolved into the corridor: a reader
// looking at "United Kingdom & Europe" wants to see which countries are in it.
const merged = Object.fromEntries(Object.entries(groups)
  .map(([k, rs]) => [k, rs.map((r) => r.map(robinson))]))
const fit = fitter(Object.values(merged), 1000, 4)

const TOL = 0.45
const out = {}
let pts = 0
for (const [k, rings] of Object.entries(merged)) {
  const rs = rings.map((r) => simplify(r.map(fit.at), TOL))
    // A cut at the seam can leave a hairline strip; below a pixel of area it is
    // not a country, it is an artefact.
    .filter((r) => r.length > 3 && area2(r) > 2)
  pts += rs.reduce((n, r) => n + r.length, 0)
  out[k] = path(rs)
}

const body = `/* Generated from Natural Earth 110m country boundaries, grouped into the
   corridors the international book travels and kept whole inside them. Source: world-atlas@2 (TopoJSON),
   Robinson projection, simplified to ${TOL}px at this viewBox. Antarctica is
   left off. Regenerated by scratchpad/build-world.mjs. */

export const WORLD = {
  viewBox: '0 0 1000 ${fit.height.toFixed(0)}',
  // Everywhere the book does not reach, drawn once as a silhouette.
  rest: '${out.rest}',
  // The issuing market itself, so the map says where home is.
  home: '${out.home}',
  corridors: {
${ORDER.map((w) => `    ${w}: '${out[w]}',`).join('\n')}
  },
}
`
fs.writeFileSync(`${OUT}/src/data/geo/world.js`, body)
console.log(`world: ${pts} points, ${(body.length / 1024).toFixed(1)} KB, viewBox 0 0 1000 ${fit.height.toFixed(0)}`)
for (const k of ['rest', 'home', ...ORDER]) console.log(`  ${k.padEnd(5)}: ${(out[k].match(/M/g) || []).length} rings, ${(out[k].length / 1024).toFixed(1)} KB`)
