import fs from 'node:fs'
import { area2, dissolve, fitter, inside, mercator, path, simplify, stitch } from './geolib.mjs'

const S = process.argv[2]
const OUT = process.argv[3]
const g = JSON.parse(fs.readFileSync(`${S}/india.geojson`, 'utf8'))

// Which zone each state belongs to. Written out because "Sikkim is North-East"
// is a convention, not something a bounding box can work out.
const ZONE = {}
const put = (z, ...ss) => ss.forEach((s) => { ZONE[s] = z })
put('z1', 'Delhi', 'Uttar Pradesh', 'Punjab', 'Haryana', 'Rajasthan', 'Himachal Pradesh',
  'Uttarakhand', 'Jammu and Kashmir', 'Ladakh', 'Chandigarh')
put('z2', 'Assam', 'Meghalaya', 'Tripura', 'Manipur', 'Mizoram', 'Nagaland',
  'Arunachal Pradesh', 'Sikkim')
put('z3', 'Maharashtra', 'Gujarat', 'Goa', 'Dadra and Nagar Haveli and Daman and Diu')
put('z4', 'Madhya Pradesh', 'Chhattisgarh')
put('z5', 'West Bengal', 'Odisha', 'Bihar', 'Jharkhand')
put('z6', 'Karnataka', 'Tamil Nadu', 'Telangana', 'Kerala', 'Andhra Pradesh',
  'Puducherry', 'Lakshadweep', 'Andaman and Nicobar Islands')

const ORDER = ['z1', 'z2', 'z3', 'z4', 'z5', 'z6']

const raw = {}
for (const f of g.features) {
  const z = ZONE[f.properties.st_nm]
  if (!z) throw new Error(`unmapped state ${f.properties.st_nm}`)
  const polys = f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates
  ;(raw[z] ||= []).push(...polys.flat())
}

const merged = Object.fromEntries(ORDER.map((z) => [z, stitch(dissolve(raw[z])).map((r) => r.map(mercator))]))
const fit = fitter(Object.values(merged), 1000, 4)

const TOL = 0.55
const zones = {}
let pts = 0
for (const z of ORDER) {
  const all = merged[z]
    .map((r) => simplify(r.map(fit.at), TOL))
    .filter((r) => r.length > 3)
    .sort((a, b) => area2(b) - area2(a))
  // A state that sits wholly inside another one in the same zone — Chandigarh,
  // Puducherry, Dadra & Nagar Haveli — leaves its border behind when the
  // vertices on the two sides of it do not match. Those are internal lines, not
  // coastline, so they come out. An island is kept: it is inside nothing.
  const rings = all.filter((r, i) => !all.slice(0, i).some((big) => inside(r[0], big)))
  pts += rings.reduce((n, r) => n + r.length, 0)
  zones[z] = path(rings)
}

const body = `/* Generated from district boundaries, dissolved into the six zones.
   Source: udit-001/india-maps-data (district GeoJSON), Mercator, simplified to
   ${TOL}px at this viewBox. Regenerated by scratchpad/build-india.mjs. */

export const INDIA = {
  viewBox: '0 0 1000 ${fit.height.toFixed(0)}',
  zones: {
${ORDER.map((z) => `    ${z}: '${zones[z]}',`).join('\n')}
  },
}
`
fs.mkdirSync(`${OUT}/src/data/geo`, { recursive: true })
fs.writeFileSync(`${OUT}/src/data/geo/india.js`, body)
console.log(`india: ${ORDER.length} zones, ${pts} points, ${(body.length / 1024).toFixed(1)} KB, viewBox 0 0 1000 ${fit.height.toFixed(0)}`)
for (const z of ORDER) console.log(`  ${z}: ${(zones[z].match(/M/g) || []).length} rings, ${(zones[z].length / 1024).toFixed(1)} KB`)
